SQL> SHUTDOWN IMMEDIATE;

SQL> STARTUP MOUNT;

SQL> ALTER DATABASE ARCHIVELOG;

SQL> ALTER SYSTEM SET log_archive_dest_1='LOCATION=/u01/app/oracle/oradata/archivelog' SCOPE=SPFILE;

SQL> ALTER DATABASE OPEN;

SQL> ARCHIVE LOG LIST;

SQL> SELECT log_mode FROM v$database;
